export const FILL_TODOS = "FILL_TODOS"
export const ADD_TODO = "ADD_TODO"
export const COMPLETED_TODO = "COMPLETED_TODO" 
export const IMPORTANT_TODO = "IMPORTANT_TODO" 
export const DELETE_TODO = "DELETE_TODO" 